name: Copilot Setup

on: []

permissions: {}

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: denoland/setup-deno@v2
