name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@v2

      - name: Publish
        run: deno publish
