name: Title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: denoland/setup-deno@v2

      - name: Check PR title
        run: deno run -A jsr:@roka/forge title --verbose "$TITLE" --types \
          build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test
        env:
          TITLE: ${{ github.event.pull_request.title }}
