name: Title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: denoland/setup-deno@v2

      - name: Check PR title
        run: deno task forge title "$TITLE" \
          --strict \
          --types build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test
        env:
          TITLE: ${{ github.event.pull_request.title }}
